language: python
python:
- 3.6
sudo: required
install:
- nvm install 10
- nvm use 10
- pip install virtualenv
- virtualenv ~/env
- source ~/env/bin/activate
- pip install transifex-client PyYAML requests awesome-slugify
- sudo echo $'[https://www.transifex.com]\nhostname = https://www.transifex.com\nusername = '"$TRANSIFEX_USER"$'\npassword = '"$TRANSIFEX_PASSWORD"$'\ntoken = '"$TRANSIFEX_API_TOKEN"$'\n' > ~/.transifexrc
- npm install
- npm install -g @angular/cli@7.1.3
script:
- python tools/yaml_to_json.py
- ng lint
- ". extract_i18n.sh"
- tx push --source
- tx pull --mode sourceastranslation -l ar,he,en,km_KH,am,ru,es,fr
- ng build --prod -c production
- ng build --prod -c ar
- ng build --prod -c en
- ng build --prod -c he
- ng build --prod -c km_KH
- ng build --prod -c ru
- ng build --prod -c es
- ng build --prod -c fr
- python tools/yaml_to_json.py
deploy:
  provider: heroku
  api_key:
    secure: jhxWPPa4To+WA7mTbnvPnFJpfykem4iGeSj39/Ck9z/GtcS56JjgitlJZ7w1DoP3mCPrznErc1pNEK2xDY5xfQlMxX8KkecrLpp9jhQ5RTgdYF9QnxrvkwrGBTr8/pNt2hgdZ4jcuTpFGBOhcGIZv5sD97vqlpiUOWyMYYfxLmFVFBcRgfPJuIJmiVDPw/2mn7CbwPQMlHeebqX3oRb99OecL0loI2IIpD2rFQlsFBbIfQpksq5MjS9wrlOuONgLm0WH3TgzKppKuoWU4z+LNoPymB+kLxEjbMNQ9j1Hy7fqVIwIv4ZIonNJZ/Wu7yudrFzpynHhodEe8+pGaUZ7bDvlLUFL5j2QNwAQFFnOutU4PgQqxLVXnsiFoJDTgsVjdNf21beLX3xislHGiDUle1TDZkqu9ehblZ9yzRA736ue5QYWoGXUHiM3NwFLEtoAPeV0/xA3eylZ+5bNptQHpIel2Sg+28yfGZfcYyDmvd/deX4df9/IjEjrDnc7573uUgkEXMHCWeylTyfFhr2csMLxBVNsvnOddN7bBJt13skeXl4o63mZT2zjMA6DWOB62vAHRQdgU01PYispmh8Lj0snnl7mRj8UakecHRvHs5G7sGuP5jp8Ngo/soN2WOwgVBfdwqG0Hsmo4rutEmSuJz9V7c5PEJIyoSCXC7YYvx0=
  app: avid-covider
  on:
    repo: radinreth/avid-covider
env:
  global:
    secure: PAvs9kwjmGT/t12UHSgaVBVYtEBwQDVrvUXD3Un3bnQPiyr/D4dfr/mZGNt2kvkuwCe0fkZe6bBL+RCdwW8M5HZlx2QmiNLxJNFHCAGoXear0MMLMAOgQ5cCYyFkycnd/3cIM0GKVRt+LEg9DDLx9ZtdftlJ/5mgMT7QpCRFpIZyzqNkV4t4B26SULR1pf6ZM0n+7lCwOeiR3sTGUHB3sLNRx6AfTN+CKUyDG40LtZ2Iym1md/VjjXLOlVFW0vaK9M2xNIAlEc0TWTauj4QBAenXS/x84cL9tqEBz/od2ERJX9XSMcWkM2q2Kslfgg56F03r1hkNs54iWwHW2gukwZf82z1JvQST0noMDdWfbEXQT+aGraXNaeJiT1VDi752WPDtg6e29ElpAxdROBbTgtuca1Kl+Ojh7YhI9CDq2PWR2nU8hXkimkxls/sVwOEKCQBLTyivOEMlqLtO0VPdKPV923pjx+w7fJxlfBMKRUJ8qrCyfijiZ4HzXyC/QL7VfbEawvQzZuk9/0s+Jli8uyoHZ71S24SeTCz+MtVp2rTBudPRC6nH78Fi8Osl3KGkpu2vFuIVvYBbt0q8iZlhGv7YmAOeEvbdmw7d0tWW00PzyTlDJiNurieYGArLip0TDUj9ef5Aqp9qcu5s1h+gscrCOJK9AV8d5i+P4+TC4Dw=
