version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
    ports: 
      - '4200:4200'
    command:
      bash -c "npm install && ng serve --host 0.0.0.0 --verbose true"
